/** nrf8001 example project 
 */

#include <avr/io.h>
#include <util/delay.h>
#include <avr/interrupt.h>

#include "spi.h"
#include "hardware.h"

#include "hal_aci_tl.h"
#include "aci.h"
#include "aci_evts.h"
#include "aci_cmds.h"
#include "lib_aci.h"

#include "config.h"

#include "ble_interface.h"

#define W25Q_SS_PIN 1

#define LOGIC_LOW   0
#define LOGIC_HIGH  1

extern uint8_t rdynFlag;

/*  aci_struct that will contain:
*       total initial credits
*       current credit
*       current state of the aci (setup/standby/active/sleep)
*       open remote pipe pending
*       close remote pipe pending
*       Current pipe available bitmap
*       Current pipe closed bitmap
*       Current connection interval, slave latency and link supervision timeout
*       Current State of the the GATT client (Service Discovery)
*       Status of the bond (R) Peer address
*/
static struct aci_state_t aci_state;
static hal_aci_evt_t aci_data;
static hal_aci_data_t aci_cmd;

/** Function Prototypes **/
void resetDevice(void);

int main(void)
{

    NRF8001_RSTN_CONFIG_OUT;
    NRF8001_REQN_CONFIG_OUT;

    SET_RSTN_HIGH();            // Set RST high
    //SET_REQN_HIGH();

    //This will reset the nRF8001. ACI Device Started Event is generated by the nRF8001 device
    //as soon as the reset is complete
    hal_aci_tl_init();

    _delay_ms(100);
    sei();

    // Reset the device
    resetDevice();
    //LED2_CONFIG_OUT;

    _delay_ms(100);

    begin_BLE(&aci_state);
    while(1)
    {
        if(rdynFlag == 1)
        {
            rdynFlag = 0;
            m_rdy_line_handle();
        }
        pollACI(&aci_state, &aci_data, &aci_cmd);
    }
    return 1;
}

/** @brief: resets the nrf8001 breakout
*/
void resetDevice(void)
{
    NRF8001_RSTN_CONFIG_OUT;    // Configure AVR PB0 as RST
    
    SET_RSTN_HIGH();            // Set RST high
    _delay_ms(50);               
    SET_RSTN_LOW();             // Set RST low
    _delay_ms(100);               
    SET_RSTN_HIGH();            // Set RST high
    _delay_ms(100);               
  
    SET_RSTN_HIGH();            // Set RST high
}
